/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yitian_practice_jni_HelloWorld */

#ifndef _Included_com_yitian_practice_jni_HelloWorld
#define _Included_com_yitian_practice_jni_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yitian_practice_jni_HelloWorld
 * Method:    say
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yitian_practice_jni_HelloWorld_say
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
